### ISSUE TITLE
Get "NoneType" exception and fail to perform cold-boot and warm-boot stress test 

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#654] opened 2023-08-09 01:31 UTC
### Problem

Unable to perform `cold-boot-loop-reboot1` and `warm-boot-loop-reboot1` since the `TypeError: 'NoneType' object is not iterable`  exception be thrown.

This issue can be 100% reproduced by installing Checkbox22 Version: 2.9.0 (Rev: 473), but no this problem while using Checkbox22 Version: 2.8.0 (Rev: 437).

```
---------------------------[ Perform cold reboot 1 ]----------------------------
ID: com.canonical.certification::cold-boot-loop-reboot1
Category: com.canonical.certification::stress-tests/cold-boot
Waiting for the system to shut down or reboot...
Traceback (most recent call last):
  File "/snap/checkbox22/current/bin/checkbox-cli", line 8, in <module>
    sys.exit(main())
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/checkbox_cli.py", line 163, in main
    subcmd.invoked(ctx)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/subcommands.py", line 261, in invoked
    self._run_jobs(self.ctx.sa.get_dynamic_todo_list())
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/stages.py", line 375, in _run_jobs
    builder = self._run_single_job_with_ui_loop(
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/stages.py", line 189, in _run_single_job_with_ui_loop
    result_builder = self.sa.run_job(job.id, ui, False)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/impl/decorators.py", line 142, in wrapper
    raise exc
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/impl/decorators.py", line 136, in wrapper
    return func(*args, **kwargs)
  File "/snap/checkbox22/current/lib/python3.10/site-packages/plainbox/impl/session/assistant.py", line 1443, in run_job
    for cmd_part in self._restart_cmd_callback(
  File "/snap/checkbox22/current/lib/python3.10/site-packages/checkbox_ng/launcher/subcommands.py", line 312, in <lambda>
    lambda session_id: [shlex.join(respawn_cmd.append(session_id))]
  File "/snap/checkbox22/current/usr/lib/python3.10/shlex.py", line 320, in join
    return ' '.join(quote(arg) for arg in split_command)
TypeError: 'NoneType' object is not iterable
```

### To Reproduce

1. Install checkbox22 snap 2.9 version
2. Run `cold-boot-loop-reboot1` and `warm-boot-loop-reboot1` tests in Stress Test Plan

### Environment

- OS: Server Image 22.04
- Checkbox Type: Snap
- Checkbox Version: 2.9.0 2023-08-08 (473)
- Architecture: arm64

**Comment by pieqq** [comment] 2023-08-09 05:28
The issue is from [this change in subcommands.py](https://github.com/canonical/checkbox/blob/main/checkbox-ng/checkbox_ng/launcher/subcommands.py#L312):

```
            lambda session_id: [shlex.join(respawn_cmd.append(session_id))]
```

This is because `shlex.join()` expects an iterable, but `list.append()` actually returns None :)

I've got a fix for this, but I'm now trying to build a snap to test it on a local device.

**Closed** 2023-08-09 09:40 UTC
Labels: bug, Critical
