### ISSUE TITLE
LP1905097: Remote test session paused indefinitely when session was disconnected

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#150] opened 2022-11-28 16:32 UTC
This issue was migrated from https://bugs.launchpad.net/checkbox-ng/+bug/1905097

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| Triaged	| 2020-11-20 22:31:27	| 6	| Low	| False  	|

## Description
Honestly, I have no idea how to reproduce this.  I discovered it while looking into this bug against testflinger:

https://bugs.launchpad.net/testflinger/+bug/1905094

In that bug, note the second disconnect example for Drapion.  In that case, testflinger showed that there was a disconnection and then it was never able to reconnect, and eventually the testflinger instance exited.

Now in the course of investigating that, I got the idea to just try connecting manually to the SUT via checkbox remote myself.  I had expected to find that the test session had completed silently in the background.  What I found instead, was that the test session (which is fully automated, including submission to C3) had paused and only resumed testing after I manually connected to the session from my own desktop.  

As the remote sessions are supposed to continue running headless, I'm a bit baffled as to why this one paused execution and waited for me to manually reconnect.

Also note, despite what the error messages in the above bug say, I did NOT, at any time, connect to the checkbox session from anywhere else.  I merely fired off testflinger and walked away to wait for them to complete.  I only connected to the session a couple days after the fact, expecting to find it already completed.

## Attachments
No attachments

Tags:
['hwcert-server']

**Comment by Hook25** [comment] 2024-01-10 08:06
Remote sessions are not supposed to continue headless, they do need the controller by design. Closing this. If I misunderstood the issue please do reopen it and tag me

**Closed by Hook25** 2024-01-10 08:06 UTC
Labels: bug, FromLaunchpad
