### ISSUE TITLE
"environment" section is not consumed (but it worked with checkbog-ng version 2.6~ppa~ubuntu18.04.1)

### ISSUE THREAD

**Issue by tai271828** [canonical/checkbox#651] opened 2023-08-04 09:13 UTC
### Bug Description

"environment" section in a launcher is not consumed by checkbox-ng `2.9.dev52+gc71db97b4~ubuntu18.04.1 `. However it would work with checkbog-ng version `2.6~ppa~ubuntu18.04.1`.

### To Reproduce

1. Install canonical-certification-server from Checkbox dev PPA
2. Run the example launcher by simple `./server-bug-reproducer`[1].

[1] The example launcher, `server-bug-reproducer`:
```
#!/usr/bin/env checkbox-cli

[launcher]
app_id = com.canonical.certification:testlauncher
launcher_version = 1
stock_reports = submission_files

[test plan]
unit = com.canonical.certification::server-regression
forced = yes

[test selection]
exclude = com.canonical.certification::cpu/clocktest com.canonical.certification::cpu/cpufreq_test-server com.canonical.certification::disk/.* com.canonical.certification::memory/.*
forced = yes

[ui]
type = silent
#output = hide

[environment]
#STRESS_NG_DISK_TIME = 30
STRESS_NG_CPU_TIME = 30
# not implemented yet
#STRESS_NG_MEMORY_TIME = 30
```

### Environment

- OS: Ubuntu Bionic
- Checkbox Type: Debian
- Checkbox Version: 2.6~ppa~ubuntu18.04.1
- Hardware being tested: this is a userspace issue and should be across platforms.

### Relevant log output

```shell
I expected log output like this if the variable `STRESS_NG_CPU_TIME` from the environment section of the example launcher is consumed correctly (the the corresponding job will be much shorter):


---------------------[ Stress of CPUs (very long runtime) ]---------------------
ID: com.canonical.certification::stress/cpu_stress_ng_test
Category: com.canonical.plainbox::stress                                                                              
... 8< -------------------------------------------------------------------------
Found STRESS_NG_CPU_TIME env var, stress_ng cpu running time is now: 30 seconds
Estimated total run time is 0 minutes 
                                                           
04 Aug 08:51: Running multiple stress-ng stressors in parallel for 30
seconds...                 
stress-ng: info:  [40498] setting to a 30 second run per stressor                                                                                                                                                                            
stress-ng: info:  [40498] dispatching hogs: 46 af-alg, 46 bsearch, 46 context, 46 cpu, 46 crypt, 46 hsearch, 46 longjmp, 46 lsearch, 46 matrix, 46 qsort, 46 str, 46 stream, 46 tsearch, 46 vecmath, 46 wcs
stress-ng: info:  [40499] af-alg: 82 cryptographic algorithms found in /proc/crypto
stress-ng: info:  [40499] af-alg: 124 cryptographic algorithms in total (with defconfigs)
stress-ng: info:  [40499] af-alg: 4 cryptographic algorithms are internal and may be unused
stress-ng: info:  [42119] qsort: using method 'qsort-libc'
stress-ng: info:  [42328] stream: using built-in defaults as no suitable cache found
stress-ng: info:  [42328] stream: stressor loosely based on a variant of the STREAM benchmark code
stress-ng: info:  [42328] stream: do NOT submit any of these results to the STREAM benchmark results
stress-ng: info:  [42328] stream: Using CPU cache size of 2048K
stress-ng: info:  [42334] stream: memory rate: 4468.29 MB read/sec, 2978.86 MB write/sec, 390.45 Mflop/sec (instance 5)
stress-ng: info:  [42343] stream: memory rate: 2467.76 MB read/sec, 1645.18 MB write/sec, 215.64 Mflop/sec (instance 13)

```

If the variable is not parsed, the log would show:
```
---------------------[ Stress of CPUs (very long runtime) ]---------------------
ID: com.canonical.certification::stress/cpu_stress_ng_test
Category: com.canonical.plainbox::stress
... 8< -------------------------------------------------------------------------
STRESS_NG_CPU_TIME env var is not found, stress_ng cpu running time is default value
```

### Additional context

I did not exercise comprehensive bisecting. However, fwiw, a quick look tells me:
- The issue was introduced after v2.7 or above.
- Probably this commit? 40733bda6169f4dc112a7608ec41cab5d95e74b8
- Maybe related to this issue as well https://github.com/canonical/checkbox/issues/446

**Comment by Hook25** [comment] 2023-08-04 13:14
Thank you for this very detailed report, I think I have found the problem, the issue is that while moving to the new config parsing we accidentally made it case-insensitive. 

You can track #653 to see when it will be resolved in main/edge.

**Closed** 2023-08-07 01:53 UTC
Labels: bug

**Comment by pieqq** [comment] 2023-08-07 01:54
@tai271828 早！This fix has been merged and should be available in edge/daily PPA soon. Please try it and let us know if things are working as expected now.
