### ISSUE TITLE
usb3/storage-automated test failed due to the xhci driver check in checkbox only allows xhci_hcd

### ISSUE THREAD

**Issue by baconYao** [canonical/checkbox#723] opened 2023-09-14 05:27 UTC
### Bug Description

usb3/storage-automated test failed due to the xhci driver check in checkbox only allows xhci_hcd
usb3/storage-automated test relies on removable_storage_test.py and it requires a argument "--driver" when running the test, in the current implementation it's providing "xhci_hcd" for the script to check but on Baoshan G1200-evk device the driver being used is "xhci-mtk".

### To Reproduce

1. Install checkbox22 and checkbox-baoshan-classic
  $ sudo snap install checkbox22 --beta
  $ sudo snap install checkbox-baoshan-classic --classic --edge
2. Insert the USB3 drive to any of the USB3 ports on G1200-evk
3. Start running the test
  $ checkbox-baoshan-classic.checkbox-cli run com.canonical.certification::usb3/storage-automated

### Environment

- CID: 202303-31430
- OS: Jammy Server (iot-baoshan-classic-server-2204-x06-20230908-114)
- Checkbox Type: Snap

### Relevant log output

```shell
dmesg output when the usb3 drive is plugged into G1200-evk:

[ 1636.058071] usb 8-1.1: new SuperSpeed USB device number 4 using xhci-mtk
[ 1636.083917] usb 8-1.1: New USB device found, idVendor=0781, idProduct=5591, bcdDevice= 1.00
[ 1636.090503] usb 8-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1636.096935] usb 8-1.1: Product: Ultra USB 3.0
[ 1636.100364] usb 8-1.1: Manufacturer: SanDisk
[ 1636.103350] usb 8-1.1: SerialNumber: 4C530000151115102553
[ 1636.107593] usb-storage 8-1.1:1.0: USB Mass Storage device detected
[ 1636.111478] scsi host1: usb-storage 8-1.1:1.0
[ 1636.118455] pwm-backlight backlight_lcd0: supply power not found, using dummy regulator
[ 1637.144279] scsi 1:0:0:0: Direct-Access SanDisk Ultra USB 3.0 1.00 PQ: 0 ANSI: 6
[ 1637.154118] sd 1:0:0:0: Attached scsi generic sg0 type 0
[ 1637.167084] sd 1:0:0:0: [sda] 30031872 512-byte logical blocks: (15.4 GB/14.3 GiB)
[ 1637.183391] sd 1:0:0:0: [sda] Write Protect is off
[ 1637.193417] sd 1:0:0:0: [sda] Mode Sense: 43 00 00 00
[ 1637.208690] sd 1:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[ 1637.237176] sda: sda1
[ 1637.260332] sd 1:0:0:0: [sda] Attached SCSI removable disk
```

### Additional context

This driver is already in upstream.

- https://github.com/torvalds/linux/blob/master/drivers/usb/host/xhci-mtk.c

**Comment by baconYao** [comment] 2024-03-22 06:39
Issue can still be reproduced.

Submission: https://certification.canonical.com/hardware/202307-31864/submission/361476/test-results/fail/

CID: 202307-31864
SKU: G1200
Image: iot-baoshan-classic-desktop-2204-x01-20231005-133
kernel-version: 5.15.0-1029-mtk

**Snap**
```
ubuntu@mtk-genio:~$ sudo snap list
Name                       Version           Rev    Tracking         Publisher            Notes
bare                       1.0               5      latest/stable    canonical✓           base
checkbox                   4.0.0-dev139      6105   latest/beta      ce-certification-qa  classic
checkbox22                 4.0.0-dev139      834    latest/beta      ce-certification-qa  -
```

**Comment by LiaoU3** [comment] 2024-06-27 07:10
Issue can still be reproduced.

https://certification.canonical.com/hardware/202406-34152/submission/376847/

**Comment by pieqq** [comment] 2024-08-02 07:53
An easy thing would be to have a list of modules to look for, but as @zongminl mentioned in a meeting, the list might go on (for instance, we have Mediatek implementation, but also Qualcomm, NVIDIA, etc.).

Looks like Checkbox job only uses the `xhci_hcd` for information, so we could just work around this.

**Comment by pieqq** [comment] 2024-08-22 12:48
After looking at this issue again, it looks like the script called has been replaced when Fernando worked on #1291 a month ago.

@baconYao @LiaoU3 could you check with a recent version of Checkbox if this problem still happens?

**Comment by LiaoU3** [comment] 2024-08-27 02:25
I did not observe this issue now.
```
checkbox22                  4.2.0-dev9     1057   latest/beta    ce-certification-qa  -
```
```
ubuntu@ubuntu:~$ checkbox-riverside-classic.checkbox-cli run com.canonical.certification::usb3/storage-automated
$PROVIDERPATH is defined, so following provider sources are ignored ['/snap/checkbox-riverside-classic/x1/providers/checkbox-provider-riverside', '/home/ubuntu/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
Using sideloaded provider: checkbox-provider-riverside, version 0.1 from /var/tmp/checkbox-providers/checkbox-provider-riverside
Skipped file: /snap/checkbox22/current/providers/checkbox-provider-base/units/stress/suspend_cycles_reboot.md
===========================[ Running Selected Jobs ]============================
==============[ Running job 1 / 3. Estimated time left: 0:07:00 ]===============
--------------[ Collect information about supported types of USB ]--------------
ID: com.canonical.certification::usb
Category: com.canonical.certification::information_gathering
... 8< -------------------------------------------------------------------------
usb2: supported
usb3: supported
------------------------------------------------------------------------- >8 ---
Outcome: job passed
==============[ Running job 2 / 3. Estimated time left: 0:07:00 ]===============
-----------------[ USB 3.0 storage device insertion detected ]------------------
ID: com.canonical.certification::usb3/insert
Category: com.canonical.plainbox::usb
Purpose:

Check system can detect insertion of a USB 3.0 storage device.
NOTE: Make sure the USB storage device has a partition before starting
the test.

Steps:

1. Press continue.
2. Wait until the message "INSERT NOW" is displayed on the screen.
3. Connect USB 3.0 storage device.

Pick an action
    => press ENTER to continue
  c => add a comment
  s => skip this job
  q => save the session and quit
[csq]: 
... 8< -------------------------------------------------------------------------


INSERT NOW


Timeout: 30 seconds
super_speed_usb was inserted. Controller: None, Number: None
usable partition: sda1
USB3 insertion test passed.
cache file usb_insert_info is at: /var/tmp/checkbox-ng/sessions/checkbox-run-2024-08-27T02.22.56.session/session-share
------------------------------------------------------------------------- >8 ---
Outcome: job passed
==============[ Running job 3 / 3. Estimated time left: 0:05:00 ]===============
-----------------[ USB 3.0 storage device read & write works ]------------------
ID: com.canonical.certification::usb3/storage-automated
Category: com.canonical.plainbox::usb
... 8< -------------------------------------------------------------------------
DEBUG:generating a random file
DEBUG:try to mount usb storage for testing
DEBUG:mount /dev/sda1 on /tmp/tmphhnmnwrs successfully.
DEBUG:===================
DEBUG:writing test begins
DEBUG:===================
DEBUG:Apply command: ['dd', 'if=/tmp/tmpbzhdkx7m', 'of=/tmp/tmphhnmnwrs/tmpbzhdkx7m0', 'bs=1M', 'oflag=sync']
DEBUG:['100+1 records in', '100+1 records out', '104858730 bytes (105 MB, 100 MiB) copied, 2.68134 s, 39.1 MB/s', '']
DEBUG:No I/O errors found in dmesg
PASS: WRITING TEST: /tmp/tmphhnmnwrs/tmpbzhdkx7m0
DEBUG:Apply command: ['dd', 'if=/tmp/tmpbzhdkx7m', 'of=/tmp/tmphhnmnwrs/tmpbzhdkx7m1', 'bs=1M', 'oflag=sync']
DEBUG:['100+1 records in', '100+1 records out', '104858730 bytes (105 MB, 100 MiB) copied, 3.70878 s, 28.3 MB/s', '']
DEBUG:No I/O errors found in dmesg
PASS: WRITING TEST: /tmp/tmphhnmnwrs/tmpbzhdkx7m1
DEBUG:Apply command: ['dd', 'if=/tmp/tmpbzhdkx7m', 'of=/tmp/tmphhnmnwrs/tmpbzhdkx7m2', 'bs=1M', 'oflag=sync']
DEBUG:['100+1 records in', '100+1 records out', '104858730 bytes (105 MB, 100 MiB) copied, 4.72586 s, 22.2 MB/s', '']
DEBUG:No I/O errors found in dmesg
PASS: WRITING TEST: /tmp/tmphhnmnwrs/tmpbzhdkx7m2
DEBUG:Apply command: ['dd', 'if=/tmp/tmpbzhdkx7m', 'of=/tmp/tmphhnmnwrs/tmpbzhdkx7m3', 'bs=1M', 'oflag=sync']
DEBUG:['100+1 records in', '100+1 records out', '104858730 bytes (105 MB, 100 MiB) copied, 5.6746 s, 18.5 MB/s', '']
DEBUG:No I/O errors found in dmesg
PASS: WRITING TEST: /tmp/tmphhnmnwrs/tmpbzhdkx7m3
DEBUG:Apply command: ['dd', 'if=/tmp/tmpbzhdkx7m', 'of=/tmp/tmphhnmnwrs/tmpbzhdkx7m4', 'bs=1M', 'oflag=sync']
DEBUG:['100+1 records in', '100+1 records out', '104858730 bytes (105 MB, 100 MiB) copied, 5.70635 s, 18.4 MB/s', '']
DEBUG:No I/O errors found in dmesg
PASS: WRITING TEST: /tmp/tmphhnmnwrs/tmpbzhdkx7m4
Average writing speed is: 25.300 MB/s (5x100.0 MB files were written)
DEBUG:===================
DEBUG:reading test begins
DEBUG:===================
DEBUG:40edf939f34b92b601f74245e6ed55de /tmp/tmphhnmnwrs/tmpbzhdkx7m0 (verified)
DEBUG:40edf939f34b92b601f74245e6ed55de /tmp/tmpbzhdkx7m (source)
PASS: READING TEST: /tmp/tmphhnmnwrs/tmpbzhdkx7m0 passes md5sum comparison.
DEBUG:40edf939f34b92b601f74245e6ed55de /tmp/tmphhnmnwrs/tmpbzhdkx7m1 (verified)
DEBUG:40edf939f34b92b601f74245e6ed55de /tmp/tmpbzhdkx7m (source)
PASS: READING TEST: /tmp/tmphhnmnwrs/tmpbzhdkx7m1 passes md5sum comparison.
DEBUG:40edf939f34b92b601f74245e6ed55de /tmp/tmphhnmnwrs/tmpbzhdkx7m2 (verified)
DEBUG:40edf939f34b92b601f74245e6ed55de /tmp/tmpbzhdkx7m (source)
PASS: READING TEST: /tmp/tmphhnmnwrs/tmpbzhdkx7m2 passes md5sum comparison.
DEBUG:40edf939f34b92b601f74245e6ed55de /tmp/tmphhnmnwrs/tmpbzhdkx7m3 (verified)
DEBUG:40edf939f34b92b601f74245e6ed55de /tmp/tmpbzhdkx7m (source)
PASS: READING TEST: /tmp/tmphhnmnwrs/tmpbzhdkx7m3 passes md5sum comparison.
DEBUG:40edf939f34b92b601f74245e6ed55de /tmp/tmphhnmnwrs/tmpbzhdkx7m4 (verified)
DEBUG:40edf939f34b92b601f74245e6ed55de /tmp/tmpbzhdkx7m (source)
PASS: READING TEST: /tmp/tmphhnmnwrs/tmpbzhdkx7m4 passes md5sum comparison.
PASS: all reading tests passed.
INFO:context manager exit: unmount USB storage
INFO:umount /tmp/tmphhnmnwrs successfully.
INFO:Remove temporary folders and files.
------------------------------------------------------------------------- >8 ---
Outcome: job passed
Finalizing session that hasn't been submitted anywhere: checkbox-run-2024-08-27T02.22.56
==================================[ Results ]===================================
 ☑ : Collect information about supported types of USB
 ☑ : USB 3.0 storage device insertion detected
 ☑ : USB 3.0 storage device read & write works
```

**Comment by pieqq** [comment] 2024-08-27 09:10
I'll close this issue then.

If the problem happens again, please open a new one. Thanks!

**Closed by pieqq** 2024-08-27 09:10 UTC
Labels: bug, Importance: Critical, Critical
