### ISSUE TITLE
Missing dependencies on audio tests 

### ISSUE THREAD

**Issue by dbruno74** [canonical/checkbox#413] opened 2023-04-05 08:17 UTC
### Bug Description

ODM cert test suite, Ubuntu 22.04 Server

Audio tests are missing alsa-utils dependency. In case it is not installed manually, the test fails 

### To Reproduce

1. apt install alsa-utils
2. launch alsa-mixer and mute all channels
3. Launch checkbox.odm-certification
4. Select audio test and execute

### Environment

OS: Ubuntu Server 22.04
Checkbox snap (22.04)
SUT: Intel x86 board

### Relevant log output

```shell
- Checkbox session(s) (located in `/var/tmp/checkbox-ng/sessions/`, you usually want to select the most recent one)

- logs from the impacted components (e.g. `lsblk` if this is related to an issue when testing a disk...); a safe option is to install and run `sosreport` to gather as much log as possible.
```

**Comment by zongminl** [comment] 2023-04-10 08:38
This is a duplicate of #273

**Comment by pieqq** [comment] 2023-04-11 01:50
Closing as this is a dupe. @dbruno74 please follow #273 if you want updates about this.

**Closed by pieqq** 2023-04-11 01:50 UTC
Labels: bug
