### ISSUE TITLE
virtualization/verify_lxd_vm fails with "Error: unknown flag: --vm" on bionic

### ISSUE THREAD

**Issue by dannf** [canonical/checkbox#684] opened 2023-08-24 21:16 UTC
### Bug Description

bionic ships with a deb packaged version of lxd that does not yet support the `--vm` option, causing this test to fail.

### To Reproduce

1. `checkbox-cli run com.canonical.certification::virtualization/verify_lxd_vm`

### Environment

- Ubuntu 18.04
- I happen to be on an arm64 system, though I'm not sure architecture matters

### Relevant log output

```shell
==============[ Running job 4 / 4. Estimated time left: 0:01:00 ]===============
--------------------[ Verify LXD Virtual Machine launches ]---------------------
ID: com.canonical.certification::virtualization/verify_lxd_vm
Category: com.canonical.plainbox::virtualization
... 8< -------------------------------------------------------------------------
DEBUG:root:Executing LXD VM Test
DEBUG:root:Attempting to initialize LXD
DEBUG:root:Command lxd init --auto:
DEBUG:root: Command returned no output
DEBUG:root:Launching Virtual Machine
DEBUG:root:No local image available, attempting to import from default remote.
ERROR:root:Command lxc init ubuntu:18.04 testbed --vm  returned a code of 1
ERROR:root: STDOUT: 
ERROR:root: STDERR: Error: unknown flag: --vm

DEBUG:root:Cleaning up images and VMs created during test
ERROR:root:Command lxc image delete 34a92f221431423a904d5ae0bba99535 returned a code of 1
ERROR:root: STDOUT: 
ERROR:root: STDERR: Error: not found

ERROR:root:Command lxc delete --force testbed returned a code of 1
ERROR:root: STDOUT: 
ERROR:root: STDERR: Error: not found

FAIL: Virtual Machine was not started and checked
------------------------------------------------------------------------- >8 ---
Outcome: job failed
```

**Comment by bladernr** [comment] 2023-08-25 15:12
Closing this as it's not a checkbox bug, it's a matter of support in Bionic which is now ESM anyway... we can fix this in regression testing by installing the lxd snap, but since we don't really accept Bionic certs anymore anyway, there's nothng to do here.

I'm hesitant to require the lxd snap by default as that raises issues with labs that have significant network issues as it is (often in APAC and India) where debs work well.

**Closed by bladernr** 2023-08-25 15:12 UTC
Labels: bug

**Comment by bladernr** [comment] 2023-08-25 15:18
Also, fixing this for regression, for completeness is a matter of updating the stuff passed to testflinger to tell it to remove the lxd deb and install the snap during provisioning, without having to make more general changes to checkbox that would affect other releases. (and without having to carry bionic specific workarounds too)
