### ISSUE TITLE
LP1945633: Need to identify virtual watchdog devices

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/checkbox#195] opened 2022-11-28 17:29 UTC
This issue was migrated from https://bugs.launchpad.net/plainbox-provider-resource/+bug/1945633

## Summary
| Status 	| Created on 	| Heat 	| Importance 	| Security related 	|
|--------	|------------	|------	|------------	|------------------	|
| New	| 2021-09-30 11:37:42	| 6	| Undecided	| False  	|

## Description
Recently we see some watchdog/detect failures, but they have working watchdog function.

And we can see "virtual" watchdog device from: 

# udevadm info /dev/watchdog
N: watchdog
L: 0
E: DEVPATH=/devices/virtual/misc/watchdog
E: SUBSYSTEM=misc
E: DEVNAME=/dev/watchdog
E: MAJOR=10
E: MINOR=130

But the job watchdog/detect fails, which has command "udev_resource.py -f WATCHDOG".
We need to make sure plainbox-provider-resource/bin/udev_resource.py could detect these "virtual" watchdog devices.

## Attachments
No attachments

Tags:
[]

**Comment by yphus** [comment] 2023-06-07 19:04
Duplicate of https://github.com/canonical/checkbox/issues/201

**Closed by yphus** 2023-06-07 19:04 UTC
Labels: bug, FromLaunchpad
