### ISSUE TITLE
`checkbox-cli --version` does not work when using the snap version

### ISSUE THREAD

**Issue by pieqq** [canonical/checkbox#634] opened 2023-07-24 06:02 UTC
### Bug Description

Checkbox command line has a `--version` option, but this doesn't work with snap versions.

### To Reproduce

1. Install Checkbox snap version
2. Run `checkbox.checkbox-cli --version`

Expected output: the version of Checkbox (and providers) being used.

Actual output: `Missing parts_meta_info file.`

### Environment

- Checkbox type: snap
- Checkbox version: 2.8

**Comment by Hook25** [comment] 2023-07-26 13:05
If we get snap builds working, it should now work as intended. The parts_meta_info section and related code was removed in d0b0db97d7fa095c0474d68c8535784a6a4b583d

**Comment by Hook25** [comment] 2023-08-14 14:39
Now fixed in edge:
```
$ sudo snap install checkbox16 --channel=edge
$ sudo snap install checkbox --channel=16.04/edge --classic
$ checkbox.checkbox-cli
$PROVIDERPATH is defined, so following provider sources are ignored ['/home/h25/.local/share/plainbox-providers-1', '/var/tmp/checkbox-providers-develop'] 
2.9.dev54+g40e0469ef.d20230808
```

**Closed by Hook25** 2023-08-14 14:39 UTC
Labels: bug
